### ISSUE TITLE
Bugs in 0.7.1

### ISSUE THREAD

**Issue by charlieMonroe** [ldo/dvdauthor#19]
I'm unfortunately unable to compile the version that's here on GitHub - the bootstrap script complains about this and fails:

```
cp: /usr/share/gettext/config.rpath: No such file or directory
aclocal: error: aclocal: file '/usr/local/share/aclocal/sdl.m4' does not exist
```

I'm not very familiar with `autoconf`, so I'm not sure where to look for a culprit - I'm running OS X 10.11 with `autoconf` freshly installed.

With the latest official release, which contains a Makefile, which I can compile without any issues, I'm running into the following issues (these commands worked fine in v0.6.11):

1) Specifying chapters:

Sample commands (all have the same error output):
```
./dvdauthor -c "0,0:02:00" -t video.vob -v pal -o DVD_FOLDER
./dvdauthor -c "0,0:02:00" video.vob -v pal -o DVD_FOLDER
```

This command fails with the following ouput:

```
INFO: no default video format, must explicitly specify NTSC or PAL
ERR:  Must first specify -t, -m, or -x.
```

The same command, just without the `-c` argument works just fine - what is the correct usage?

2) After running the previous command (without the chapters argument), the DVD_FOLDER contains a DVD title. Now I want to create TOC:

```
./dvdauthor -t video.vob -v pal -o DVD_FOLDER
[...]
INFO: dvdauthor creating VTS
STAT: Picking VTS 01
[...]

./dvdauthor -T -o DVD_FOLDER

INFO: no default video format, must explicitly specify NTSC or PAL
INFO: dvdauthor creating table of contents
INFO: Scanning DVD_FOLDER/VIDEO_TS/VTS_01_0.IFO
ERR:  no video format specified for VMGM
```

After some googling, you need to set an evironment variable `export VIDEO_FORMAT=NTSC` - this should be added to the readme file here.

**Comment by ldo** [comment]
You need to specify the video format as either NTSC or PAL. This can be done in various ways, as explained [here](https://web.archive.org/web/20101027002845/http://create.freedesktop.org/wiki/Video_Format_Pref). You can also build dvdauthor with a hard-coded default format as specified to the `configure` script.

As for `config.rpath`, where does it put it on your machine?

**Comment by charlieMonroe** [comment]
Ok, I've ended up setting the environment variable.

However, I still don't understand why specifying the chapters is failing (see issue 1). Wherever I put the `-c` option with the times (as is in the Readme), I get `ERR:  Must first specify -t, -m, or -x.` I have pretty much tried all combinations. I have the following parts of the command:

- `-c` + timestamps - timestamps of chapters
- `-t` + filename - the title video file
- `-o` + output folder - directory for the output.

What's the correct format here?

Thanks!

**Comment by ldo** [comment]
I would avoid doing authoring using command-line settings. Do it with an XML file:

> dvdauthor -x *xml-file* -o|-O *out-dir*

**Comment by charlieMonroe** [comment]
Thanks, that worked well!
