### ISSUE TITLE
compat.h:147:8: error

### ISSUE THREAD

**Issue by alihanozturk** [ldo/dvdauthor#20]
dvdifo.c:87:13: warning: 'buf_write8b' defined but not used [-Wunused-function]
 static void buf_write8b
             ^
In file included from /usr/include/string.h:630:0,
                 from dvdvml.c:40:
compat.h:147:8: error: expected identifier or '(' before '__extension__'
 char * strndup
        ^
dvdauthor.c: In function 'ScanIfo':
dvdauthor.c:1110:5: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
     fread(buf, 1, 2048, h);

**Comment by ldo** [comment]
Can you give more details? What compiler?

**Comment by ldo** [comment]
No more info? Closing.
