### ISSUE TITLE
configure.am doesn't set ImageMagick cflags only the cppflags

### ISSUE THREAD

**Issue by plater** [ldo/dvdauthor#21]
Current git fails to build because ImageMagick cflags are missing, I tried to attach the patch I made but it won't upload. Here it is
cat dvdauthor-0.7.1-magick-cflags.patch
Index: configure.ac
===================================================================
--- configure.ac.orig
+++ configure.ac
@@ -51,6 +51,7 @@ AC_CHECK_PROGS(MAGICKCONFIG, [MagickCore
 if test -n "$MAGICKCONFIG"; then
     ac_save_CPPFLAGS="$CPPFLAGS"
     ac_save_LIBS="$LIBS"
+    MAGICK_CFLAGS="`$MAGICKCONFIG --cflags`"
     MAGICK_CPPFLAGS="`$MAGICKCONFIG --cppflags`"
     MAGICK_LIBS="`$MAGICKCONFIG --ldflags` `$MAGICKCONFIG --libs`"
     CPPFLAGS="$CPPFLAGS $MAGICK_CPPFLAGS"

**Comment by ldo** [comment]
I’ll have a look.

Tip: GitHub is fussy about the file extensions it will let you upload. If you rename your `.patch` file to `.patch.txt`, it will accept the upload. Also it will accept arbitrary files if they are inside `.zip` archives—so long as the total size doesn’t exceeda about 10MB.

**Comment by plater** [comment]
Should be another issue but the openSUSE build service picked up that the end of:
int main(int argc,char **argv) in mpeg2desc.c doesn't have a return, Also mpeg2desc has executable stacks.

**Comment by ldo** [comment]
It seems the problem is an inconsistency between MAGICK_CPPFLAGS being defined in configure, and MAGICK_CFLAGS being used in src/Makefile. I have changed the latter to use MAGICK_CPPFLAGS instead.

See if it builds OK for you now.

**Comment by plater** [comment]
Fixed, still got the executable stack, fixed with export LDFLAGS="$LDFLAGS -Wl,-z -Wl,noexecstack"
