### ISSUE TITLE
ImageMagick support gets disabled during configure

### ISSUE THREAD

**Issue by tgurr** [ldo/dvdauthor#22]
During configure ImageMagick gets found, but it seems to be unable to detect the "ExportImagePixels" feature:

[...]
checking for MagickCore-config... MagickCore-config
checking for ExportImagePixels... no
configure: ImageMagick does not support the function
         ExportImagePixels.  Please upgrade to ImageMagick 5.5.7 or newer
checking for MAGICK... no
[...]

Installed ImageMagick version is 6.9.7.3:

$ MagickCore-config --version
6.9.7 Q16

Happens in both, the recent 0.7.2 release and the previous 0.7.1.

**Comment by ldo** [comment]
I just did a test on my Debian Unstable system. Here is the `configure` command that worked for me:

    PATH=/home/ldo/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/x86_64-linux-gnu/ImageMagick-6.9.7/bin-q16/ ./configure

This was after installing the `libmagickcore-6.q16hdri-dev` package.

There seem to be a confusing array of ImageMagick packages, at least on Debian: libmagickwand, libmagickcore, libmagic++ ... which one(s) do you have installed? And where are you finding `MagickCore-config`?

**Comment by tgurr** [comment]
MagickCore-config resides under the host prefix, e.g `/usr/x86_64-pc-linux-gnu`:
`/usr/x86_64-pc-linux-gnu/bin/MagickCore-config`

same for the libs:
```
>-> [obj] /usr/x86_64-pc-linux-gnu/lib/libMagickWand-6.Q16.so.3.0.0
>>> [sym] /usr/x86_64-pc-linux-gnu/lib/libMagickCore-6.Q16.so.3
>>> [sym] /usr/x86_64-pc-linux-gnu/lib/libMagickCore-6.Q16.so
>-> [obj] /usr/x86_64-pc-linux-gnu/lib/libMagickCore-6.Q16.la
>-> [obj] /usr/x86_64-pc-linux-gnu/lib/libMagick++-6.Q16.so.7.0.0
>>> [sym] /usr/x86_64-pc-linux-gnu/lib/libMagickWand-6.Q16.so.3
>>> [sym] /usr/x86_64-pc-linux-gnu/lib/libMagickWand-6.Q16.so
>-> [obj] /usr/x86_64-pc-linux-gnu/lib/libMagickWand-6.Q16.la
>>> [sym] /usr/x86_64-pc-linux-gnu/lib/libMagick++-6.Q16.so.7
>>> [sym] /usr/x86_64-pc-linux-gnu/lib/libMagick++-6.Q16.so
>-> [obj] /usr/x86_64-pc-linux-gnu/lib/libMagick++-6.Q16.la
>-> [obj] /usr/x86_64-pc-linux-gnu/lib/libMagickCore-6.Q16.so.3.0.0
```
and includes:

`/usr/x86_64-pc-linux-gnu/include/ImageMagick-6/*`

only the shared data resides in `/usr/share` and of course the configurations data in `/etc/ImageMagick-6`.

pkg-config is able to find everything:

```
$ pkg-config --cflags ImageMagick
-fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/x86_64-pc-linux-gnu/include/ImageMagick-6
```
```
$ pkg-config --libs ImageMagick
-lMagickCore-6.Q16
```

**Comment by ldo** [comment]
I just did an `apt-get install libmagickcore-6.q16-dev` on my Debian Unstable system, and reran the `configure` with the additional PATH setting as I mentioned above. It seems to work for me now:

    ...
    checking for pkg-config... /usr/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for LIBPNG... yes
    checking for MagickCore-config... MagickCore-config
    checking for ExportImagePixels... yes
    ...

The version information seems slightly newer now:

    dpkg-query --showformat $'${Status;-2} ${Package;-30} ${Version;-20} ${Description;-40}\n' --show libmagickcore-6.q16-dev
    in libmagickcore-6.q16-dev        8:6.9.7.4+dfsg-1     low-level image manipulation library - d

Seems like there has been an update to ImageMagick over the last few days?

**Comment by ldo** [comment]
I have done a commit which puts back `@MAGICK_CPPFLAGS@` into `src/Makefile.am` (while keeping the addition of `@MAGICK_CFLAGS@` done to fix building with GraphicsMagick). See if that solves this problem, without causing the return of the other one.

**Comment by tgurr** [comment]
There has been a security related update to ImageMagick recently, now we're on 6.9.7.5, however the issue is till the same with your recent commit added I still get:

```
checking for MagickCore-config... MagickCore-config
checking for ExportImagePixels... no
configure: ImageMagick does not support the function
         ExportImagePixels.  Please upgrade to ImageMagick 5.5.7 or newer
checking for MAGICK... no
```

Couldn't you just use pkg-config for checking for the ImageMagick availability (like you already seem to do for GraphicsMagick) and also the right version requirement? Seems to work here manually, e.g.:

```
$ pkg-config ImageMagick --atleast-version=5.5.7 && echo TRUE || echo FALSE
TRUE
```

**Comment by ldo** [comment]
OK, I have replaced the existing code in configure.ac for finding ImageMagick with a simpler version just using `PKG_CHECK_MODULES`. See if that works better now.

**Comment by tgurr** [comment]
With your latest commit it works fine for me now, huge thanks!

**Comment by ldo** [comment]
Glad to hear it. :)
