### ISSUE TITLE
Fails to build with GraphicsMagick

### ISSUE THREAD

**Issue by tgurr** [ldo/dvdauthor#23]
Version 0.7.2 fails during compile:

[...]
checking for MagickCore-config... no
checking for MAGICK... yes
[...]

[...]
x86_64-pc-linux-gnu-cc -DHAVE_CONFIG_H -I.  -DSYSCONFDIR="\"/etc\"" -I/usr/x86_64-pc-linux-gnu/include/libxml2  -I/usr/x86_64-pc-linux-gnu/include/freetype2 -I/usr/x86_64-pc-linux-gnu/include/fribidi -I/usr/x86_64-pc-linux-gnu/include/glib-2.0 -I/usr/x86_64-pc-linux-gnu/lib/glib-2.0/include -I/usr/x86_64-pc-linux-gnu/include/freetype2 -I/usr/x86_64-pc-linux-gnu/include/libpng16 -I/usr/x86_64-pc-linux-gnu/include/harfbuzz -I/usr/x86_64-pc-linux-gnu/include/glib-2.0 -I/usr/x86_64-pc-linux-gnu/lib/glib-2.0/include -I/usr/x86_64-pc-linux-gnu/include/freetype2 -I/usr/x86_64-pc-linux-gnu/include/libpng16 -I/usr/x86_64-pc-linux-gnu/include/harfbuzz -I/usr/x86_64-pc-linux-gnu/include/glib-2.0 -I/usr/x86_64-pc-linux-gnu/lib/glib-2.0/include -pipe -O2 -march=native -Wall -pipe -O2 -march=native -c -o subgen-image.o subgen-image.c
subgen-image.c:33:24: fatal error: magick/api.h: No such file or directory
[...]

$ GraphicsMagick-config --version
1.3.25

There's also a Gentoo bugreport about the same issue already happening in 0.7.1:
https://bugs.gentoo.org/show_bug.cgi?id=459976

**Comment by ldo** [comment]
That Gentoo patch was already partly applied (the `configure.ac` part). I have added the `src/Makefile.am` part; see if that helps.

**Comment by tgurr** [comment]
Thanks! I've applied your latest commit and now it works:

$ dvdauthor --help
DVDAuthor::dvdauthor, version 0.7.2.
Build options: gnugetopt graphicsmagick iconv freetype fribidi fontconfig

**Comment by ldo** [comment]
Please check that commit 17609a2785d4ae7654183affd25e357a606a260d has not broken this.

**Comment by tgurr** [comment]
Still working for me for GraphicsMagick with your latest commit added:

```
checking for MagickCore-config... no
checking for MAGICK... yes
```
```
$ dvdauthor --help
DVDAuthor::dvdauthor, version 0.7.2.
Build options: gnugetopt graphicsmagick iconv freetype fribidi fontconfig
```
